#!/bin/zsh

local selected num
setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases 2> /dev/null
fc -pa $HISTFILE
local selected=( $(fc -rl 1 | awk '{ cmd=$0; sub(/^[ \t]*[0-9]+\**[ \t]+/, "", cmd); if (!seen[cmd]++) print $0 }' |\
FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} ${FZF_DEFAULT_OPTS-} -n2..,.. --bind=ctrl-r:toggle-sort,ctrl-z:ignore ${FZF_CTRL_R_OPTS-} --header 'Press ENTER to delete selection' --query=${(qqq)LBUFFER} +m --multi --bind 'enter:become(echo {+1})'" $(__fzfcmd)) )
local ret=$?
if [ -n "$selected[*]" ]; then
  hist delete $selected[*]
fi
zle reset-prompt
return $ret
